import AboutImage from "./about.jpg";
import { HeroImage1, HeroImage2 } from "./hero";
import {
  newsHouseImage1,
  newsHouseImage2,
  newsHouseImage3,
  newsHouseImage4,
  newsHouseImage5,
  newsHouseImage6,
  newsHouseImage7,
  newsHouseImage8,
  newsHouseImage9,
  newsHouseImage10,
  newsHouseImage11,
  newsHouseImage12,
  newsHouseImage13,
  newsHouseImage14,
  newsHouseImage15,
  newsHouseImage16,
  newsHouseImage17,
  newsHouseImage18,
  newsHouseImage19,
} from "./news-houses";
import {
  NewsImage1,
  NewsImage2,
  NewsImage3,
  NewsImage4,
  NewsImage5,
} from "./news";

export {
  AboutImage,
  HeroImage1,
  HeroImage2,
  NewsImage1,
  NewsImage2,
  NewsImage3,
  NewsImage4,
  NewsImage5,
  newsHouseImage1,
  newsHouseImage2,
  newsHouseImage3,
  newsHouseImage4,
  newsHouseImage5,
  newsHouseImage6,
  newsHouseImage7,
  newsHouseImage8,
  newsHouseImage9,
  newsHouseImage10,
  newsHouseImage11,
  newsHouseImage12,
  newsHouseImage13,
  newsHouseImage14,
  newsHouseImage15,
  newsHouseImage16,
  newsHouseImage17,
  newsHouseImage18,
  newsHouseImage19,
};
