import AboutImage from "./about.jpg";
import ContactImage from "./contact.jpg";
import HomeHeroImage from "./home-hero-image.jpg";
import { HeroImage1, HeroImage2, HeroImage3, HeroImage4 } from "./hero";
import {
  newsHouseImage1,
  newsHouseImage2,
  newsHouseImage3,
  newsHouseImage4,
  newsHouseImage5,
  newsHouseImage6,
  newsHouseImage7,
  newsHouseImage8,
  newsHouseImage9,
  newsHouseImage10,
  newsHouseImage11,
  newsHouseImage12,
  newsHouseImage13,
  newsHouseImage14,
  newsHouseImage15,
  newsHouseImage16,
  newsHouseImage17,
  newsHouseImage18,
  newsHouseImage19,
} from "./news-houses";
import {
  NewsImage1,
  NewsImage2,
  NewsImage3,
  NewsImage4,
  NewsImage5,
} from "./news";
import {
  ServicesImage1,
  ServicesImage2,
  ServicesImage3,
  ServicesImage4,
  ServicesImage5,
  ServicesImage6,
} from "./services";

export {
  AboutImage,
  HeroImage1,
  HeroImage2,
  HeroImage3,
  HeroImage4,
  NewsImage1,
  NewsImage2,
  NewsImage3,
  NewsImage4,
  NewsImage5,
  ContactImage,
  HomeHeroImage,
  ServicesImage1,
  ServicesImage2,
  ServicesImage3,
  ServicesImage4,
  ServicesImage5,
  ServicesImage6,
  newsHouseImage1,
  newsHouseImage2,
  newsHouseImage3,
  newsHouseImage4,
  newsHouseImage5,
  newsHouseImage6,
  newsHouseImage7,
  newsHouseImage8,
  newsHouseImage9,
  newsHouseImage10,
  newsHouseImage11,
  newsHouseImage12,
  newsHouseImage13,
  newsHouseImage14,
  newsHouseImage15,
  newsHouseImage16,
  newsHouseImage17,
  newsHouseImage18,
  newsHouseImage19,
};
